In [60]:
import pandas as pd

In [101]:
data = {
    'country': ['USA', 'France', 'Italy', 'Spain', 'Egypt', 'Italy', 'Italy'],
    'points': [90, 95, 87, 92, 88, 50, 70],
    'price': [30, 50, 25, 40, 20, 30, 50]
}

reviews = pd.DataFrame(data,index=[0, 1, 2, 3, 4, 5, 6])
reviews

  country  points  price
0     USA      90     30
1  France      95     50
2   Italy      87     25
3   Spain      92     40
4   Egypt      88     20
5   Italy      50     30
6   Italy      70     50

In [ ]:
reviews.iloc[1:3]

In [97]:
reviews.loc[0, 'country']

'USA'

In [98]:
reviews.iloc[:3, 0]

0       USA
1    France
2     Italy
Name: country, dtype: str

In [65]:
reviews.loc[1,"country"]

'France'

In [71]:
reviews.iloc[0:3, 2]

0    30
1    50
2    25
Name: price, dtype: int64

In [89]:
reviews.loc[:,"country"]

0       USA
1    France
2     Italy
3     Spain
4     Egypt
Name: country, dtype: str

In [93]:
reviews.set_index("price")

      country  points
price
30        USA      90
50     France      95
25      Italy      87
40      Spain      92
20      Egypt      88

In [94]:
reviews.country=="Italy"

0    False
1    False
2     True
3    False
4    False
Name: country, dtype: bool

In [95]:
reviews.loc[reviews.country=="Italy"]

  country  points  price
2   Italy      87     25

In [106]:
reviews.loc[(reviews.country=="Italy")& (reviews.points>=50)]

  country  points  price
2   Italy      87     25
5   Italy      50     30
6   Italy      70     50

In [107]:
reviews.loc[(reviews.country=="Italy")| (reviews.points>=50)]

  country  points  price
0     USA      90     30
1  France      95     50
2   Italy      87     25
3   Spain      92     40
4   Egypt      88     20
5   Italy      50     30
6   Italy      70     50

In [109]:
reviews.loc[reviews.points.isin([95, 70])]

  country  points  price
1  France      95     50
6   Italy      70     50

In [110]:
reviews.loc[reviews.price.notnull()]

  country  points  price
0     USA      90     30
1  France      95     50
2   Italy      87     25
3   Spain      92     40
4   Egypt      88     20
5   Italy      50     30
6   Italy      70     50

In [111]:
reviews['index_backwards'] = range(len(reviews), 0, -1)
reviews['index_backwards']

0    7
1    6
2    5
3    4
4    3
5    2
6    1
Name: index_backwards, dtype: int64