In [22]:
import pandas as pd

In [23]:
df = pd.read_csv('C:/Users/moham/Desktop/ai-engineer-journey/pandas-practice/students_data.csv')
df.head()

,student_id,name,age,major,gpa,city,nationality,study_hours_per_week,scholarship,graduation_year
0,1001,Mohamed,19,Electrical Engineering,2.74,Izmir,Lebanese,25,False,2028
1,1002,Ahmed,18,Software Engineering,2.42,Izmir,Syrian,36,True,2029
2,1003,Ali,22,Data Science,2.53,Ankara,Lebanese,6,True,2029
3,1004,Omar,21,Data Science,3.87,Giza,Egyptian,12,True,2029
4,1005,Hassan,21,Mathematics,3.30,Izmir,Egyptian,28,True,2026

In [24]:
df.age.describe()

count    30.000000
mean     20.666667
std       2.056668
min      18.000000
25%      19.000000
50%      21.000000
75%      22.000000
max      25.000000
Name: age, dtype: float64

In [25]:
df.city.describe()

count        30
unique        7
top       Izmir
freq          7
Name: city, dtype: object

In [26]:
df.age.mean()

np.float64(20.666666666666668)

In [27]:
df.city.unique()

<StringArray>
['Izmir', 'Ankara', 'Giza', 'Alexandria', 'Cairo', 'Istanbul', 'Bursa']
Length: 7, dtype: str

In [28]:
df.city.value_counts()

city
Izmir         7
Alexandria    7
Cairo         4
Istanbul      4
Giza          3
Bursa         3
Ankara        2
Name: count, dtype: int64

In [29]:
df.head()

,student_id,name,age,major,gpa,city,nationality,study_hours_per_week,scholarship,graduation_year
0,1001,Mohamed,19,Electrical Engineering,2.74,Izmir,Lebanese,25,False,2028
1,1002,Ahmed,18,Software Engineering,2.42,Izmir,Syrian,36,True,2029
2,1003,Ali,22,Data Science,2.53,Ankara,Lebanese,6,True,2029
3,1004,Omar,21,Data Science,3.87,Giza,Egyptian,12,True,2029
4,1005,Hassan,21,Mathematics,3.30,Izmir,Egyptian,28,True,2026

In [40]:
age_mean = df.age.mean()
df.age.map(lambda x: x-age_mean)

0    -1.666667
1    -2.666667
2     1.333333
3     0.333333
4     0.333333
5    -0.666667
6    -1.666667
7    -1.666667
8     3.333333
9    -2.666667
10   -2.666667
11   -1.666667
12    0.333333
13    0.333333
14   -2.666667
15    0.333333
16    3.333333
17    0.333333
18    4.333333
19    1.333333
20   -2.666667
21   -0.666667
22    3.333333
23    2.333333
24    1.333333
25   -0.666667
26    0.333333
27    2.333333
28   -1.666667
29   -1.666667
Name: age, dtype: float64

In [41]:
df

,student_id,name,age,major,gpa,city,nationality,study_hours_per_week,scholarship,graduation_year
0,1001,Mohamed,19,Electrical Engineering,2.74,Izmir,Lebanese,25,False,2028
1,1002,Ahmed,18,Software Engineering,2.42,Izmir,Syrian,36,True,2029
2,1003,Ali,22,Data Science,2.53,Ankara,Lebanese,6,True,2029
3,1004,Omar,21,Data Science,3.87,Giza,Egyptian,12,True,2029
4,1005,Hassan,21,Mathematics,3.30,Izmir,Egyptian,28,True,2026
5,1006,Youssef,20,Data Science,3.22,Alexandria,Lebanese,24,False,2026
6,1007,Karim,19,Software Engineering,2.34,Izmir,Syrian,20,True,2026
7,1008,Mahmoud,19,Electrical Engineering,3.46,Alexandria,Syrian,8,True,2029
8,1009,Fatima,24,Mathematics,2.33,Ankara,Egyptian,20,True,2028
9,1010,Nour,18,Software Engineering,2.76,Cairo,Syrian,10,True,2026
10,1011,Sara,18,Electrical Engineering,3.98,Cairo,Jordanian,10,True,2027
11,1012,Mariam,19,Software Engineering,3.28,Izmir,Turkish,36,True,2027
12,1013,Layla,21,Mathematics,3.11,Alexandria,Jordanian,9,True,2027
13,1014,Hana,21,Data Science,3.37,Istanbul,Egyptian,39,True,2029
14,1015,Zeinab,18,Mathematics,3.69,Bursa,Syrian,13,True,2027
15,1016,Aya,21,Data Science,3.55,Istanbul,Lebanese,13,False,2029
16,1017,Mehmet,24,Mathematics,2.46,Bursa,Turkish,35,True,2027
17,1018,Ayşe,21,Computer Science,2.06,Istanbul,Lebanese,40,True,2028
18,1019,Mustafa,25,Software Engineering,2.63,Cairo,Egyptian,15,False,2029
19,1020,Fatma,22,Software Engineering,2.54,Giza,Syrian,21,False,2027
20,1021,Emre,18,Computer Science,2.42,Cairo,Lebanese,38,True,2026
21,1022,Zeynep,20,Data Science,3.89,Bursa,Lebanese,32,True,2029
22,1023,Can,24,Software Engineering,3.75,Giza,Turkish,18,False,2026
23,1024,Elif,23,Computer Science,2.63,Alexandria,Turkish,39,True,2026
24,1025,John,22,Software Engineering,3.31,Izmir,Syrian,17,False,2026
25,1026,Maria,20,Electrical Engineering,2.79,Istanbul,Turkish,24,False,2026
26,1027,David,21,Data Science,3.83,Alexandria,Lebanese,30,True,2027
27,1028,Anna,23,Electrical Engineering,2.92,Alexandria,Lebanese,28,True,2027
28,1029,Carlos,19,Data Science,2.53,Izmir,Egyptian,33,True,2029
29,1030,Sofia,19,Computer Science,2.49,Alexandria,Lebanese,38,False,2029

In [42]:
df.age.mean()

np.float64(20.666666666666668)

In [44]:
age_mean=df.age.mean()
df.age.map(lambda x: x-age_mean)

0    -1.666667
1    -2.666667
2     1.333333
3     0.333333
4     0.333333
5    -0.666667
6    -1.666667
7    -1.666667
8     3.333333
9    -2.666667
10   -2.666667
11   -1.666667
12    0.333333
13    0.333333
14   -2.666667
15    0.333333
16    3.333333
17    0.333333
18    4.333333
19    1.333333
20   -2.666667
21   -0.666667
22    3.333333
23    2.333333
24    1.333333
25   -0.666667
26    0.333333
27    2.333333
28   -1.666667
29   -1.666667
Name: age, dtype: float64

In [ ]:
df.apply(lambda row: row*)